image: node:latest

before_script:
  - yarn global add firebase-tools

deploy:
  stage: deploy
  script:
    - yarn install
    - yarn deploy
    - firebase deploy --token $FIREBASE_TOKEN

  only:
    refs:
      - main
